### ISSUE TITLE
dpkg wrong

### ISSUE THREAD

**Issue by secwang** [justin2004/apl_in_the_shell#2]
ERROR: failed to solve: process "/bin/sh -c dpkg -i linux_64_18.2.45405_unicode.x86_64.deb" did not complete successfully: exit code: 1

**Comment by justin2004** [comment]
i just ran `make` in a bash shell and it was successful:
```
...
 => [ 6/10] RUN curl -O https://www.dyalog.com/uploads/php/download.dyalog.com/download.php?file=18.2/linux_64_18.2.45405_unicode.x86_  198.5s 
 => [ 7/10] RUN dpkg -i linux_64_18.2.45405_unicode.x86_64.deb                                                                            3.0s 
 => [ 8/10] ADD apl.sh /home/containeruser                                                                                                0.1s 
 => [ 9/10] RUN chmod 555 /home/containeruser/apl.sh                                                                                      0.3s
 => [10/10] WORKDIR /mnt                                                                                                                  0.0s
 => exporting to image                                                                                                                    2.0s
 => => exporting layers                                                                                                                   2.0s
 => => writing image sha256:2d3e6e5a2f4406d0a7e25c92af03addd8e56ecb4845f105a1020167183ec9a5b                                              0.0s
 => => naming to docker.io/justin2004/apl_in_the_shell
```

can you share your whole log (the terminal output)?

**Comment by justin2004** [comment]
@secwang , did you get it to work?

**Comment by secwang** [comment]
Sorry, I didn't get through in docker, but I called your apl.sh directly on my computer, and the work was perfect.

**Comment by secwang** [comment]
=> [ 6/10] RUN curl -O https://www.dyalog.com/uploads/php/download.dyalog.com/download.php?file=18.2/linux_64_18.2.45405_unicode.x86_64.deb                         430.1s
ERROR: failed to solve: process "/bin/sh -c dpkg -i linux_64_18.2.45405_unicode.x86_64.deb" did not complete successfully: exit code: 1
I tried to reproduce this problem, but my computer has downloaded deb on the network for too long. The problem I encountered last time should be in step 7. My environment is Mac M2.

**Comment by justin2004** [comment]
if you want the docker image to build you can try to run this instead of running `make` --
```
docker build --no-cache --build-arg=uid=`id -u` --build-arg=gid=`id -g` -t justin2004/apl_in_the_shell .
```

notice the `--no-cache`   that might help if a layer got a corrupted .deb file

**Comment by secwang** [comment]
OK, thank you.
